services:
  postgres:
    image: 'postgres:latest'
    container_name: pg-local
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "mydatabase"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "secret"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
volumes:
  pg_data: