spring:
  application:
    name: java-spring-2024

reference-data:
  categories: Телефони, Планшети, Ноутбуки
  offices:
    - name: "Магазин електроніки-1"
      contactNumber: "456-12-34"
      address:
        city: "Lviv"
        street: "Mainsquare"
        building: "22"
    - name: "Магазин електроніки-2"
      contactNumber: "789-56-34"
      address:
        city: "Kyiv"
        street: "Plosha Heroiv"
        building: "4"
    - name: "Магазин електроніки-3"
      contactNumber: "123-45-34"
      address:
        city: "Dnipro"
        street: "Mainstreet"
        building: "11"